name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/checkout@v4
        with:
          node-version: '20' # Use a Node version compatible with your dependencies

      - name: Install deps
        run: npm ci

      - name: Install Cypress binary
        run: npx cypress install

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-binary-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Run Cypress tests
        run: npm run report:full

      - name: List report files
        run: ls -R cypress/results/mocha

      # Zip all the report folder 
      - name: Zip report folder
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          zip -r report.zip cypress/results/mocha  
        
      - name: Send test report email
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
        # SMTP server details
          server_address: smtp.gmail.com  # or your SMTP
          server_port: 465                 # adjust if your SMTP uses a different port
          secure: true

        # These should be stored as GitHub Secrets
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          subject: "Cypress Test Report for ${{ github.repository }}"
          body: "The Cypress tests have completed. The Mochawesome report is attached."

          # Path to attachments. Glob works, so you can do e.g. all .html in report folder
          attachments: |
            report.zip

          to: "prem.donn@gmail.com"            # recipient(s)
          from: "CI <ci@example.com>"      # sender name and email
